declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_ENTER_ANALYTICS_ENABLED?: string;
    NEXT_PUBLIC_ENTER_ANALYTICS_TOKEN?: string;
    NEXT_PUBLIC_ENTER_PROJECT_ID?: string;
    NEXT_PUBLIC_ENTER_ANALYTICS_ENDPOINT?: string;
    NEXT_PUBLIC_ENTER_ANALYTICS_DEFINITIONS_ENDPOINT?: string;
    NEXT_PUBLIC_ENTER_ANALYTICS_DEBUG?: string;
    NEXT_PUBLIC_ASSET_BASE_URL?: string;
    NEXT_PUBLIC_XHS_CASES_CDN_URL?: string;
  }
}
